# docker run --name my-nginx -v /host/path/nginx.conf:/etc/nginx/nginx.conf:ro
# -d nginx nginx-debug -g 'daemon off;'
services:
  web:
    image: nginx
    # container_name: my-nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
    command: 
      - "nginx-debug"
      - "-g" 
      - "daemon off;"


